repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer    # Ensures files end with a newline
      - id: check-yaml           # Validates YAML files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2  # update as needed
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
